### ISSUE TITLE
hi,thank you for this nice plugin,i want ask if this line has thinkness property?

### ISSUE THREAD

**Issue by Lynnvon** [RaiaN/LineRendererComponent#1]

**Comment by RaiaN** [comment]
Hey @Lynnvon. You can achieve that through a custom Line material. Try to increase the line brightness

**Comment by Lynnvon** [comment]
> Hey @Lynnvon. You can achieve that through a custom Line material. Try to increase the line brightness

thanks for your reply,i try this but it does not work well,is there a another solution?

**Comment by RaiaN** [comment]
@Lynnvon Hi, I will try to look into that as I have time.

**Comment by RaiaN** [comment]
Thickness feature is in progress. Stay tuned

**Comment by RaiaN** [comment]
Implemented @Lynnvon
