### ISSUE TITLE
Line Position Incorrect

### ISSUE THREAD

**Issue by jiangheng90** [RaiaN/LineRendererComponent#3]
I think your line position maybe incorrect.
When I add two sphere to display the real position, It seems have deviation.
![屏幕截图 2024-02-24 011423](https://github.com/RaiaN/LineRendererComponent/assets/1418843/766d1e9d-c835-4b9a-b0db-d90ab249abe3)

**Comment by jiangheng90** [comment]
sorry I Found position is relative.

**Comment by RaiaN** [comment]
hey @jiangheng90 If you have suggestions how to improve the plugin please submit PR. There are highly appreciated!
